---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml
  - project: shore/ci-templates
    file: templates/python.yml
  - project: shore/ci-templates
    file: templates/gitlab-release.yml

install-wheel:
  extends: .install-wheel
  script:
    - template --help
    - template --version

test:
  stage: test
  image: $project:$version-slim
  before_script:
    - apt-get update
    - >-
      apt-get install -y
      bats
      build-essential
      wget
    # yamllint disable-line rule:line-length
    - wget https://github.com/cloudbees-oss/juxr/releases/download/0.1.22/juxr-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xzC /usr/local/bin
    - find dist/*.whl -exec pip install {}[all] \;
    - pip install pytest six
  script:
    - juxr tap --name bats --output results/ -- bats tests/
    - pytest --doctest-modules --junit-xml results/doctest.xml
  after_script:
  variables:
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .cache/
      - .venv/
  artifacts:
    reports:
      junit: results/*.xml
  needs:
    - job: build-wheel
      artifacts: true
  parallel:
    matrix:
      - project: python
        version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
      - project: pypy
        version:
          - "2.7"
          - "3.6"
          - "3.7"
